server:
  port: 10086
  
#基本服务信息  
spring:
  application:
    name: eureka-server #服务ID

#eureka服务器配置，单机版Eureka，不需要注册
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false    
    service-url:
     # 将自己注册到eureka-server这个Eureka上面去，暴漏Eureka服务访问地址
      defaultZone: http://localhost:${server.port}/eureka
  server:
    enable-self-preservation: false #关闭自我保护
    